# coding: utf-8
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  if Vagrant.has_plugin?('vagrant-proxyconf')
    config.proxy.enabled  = true
    config.proxy.http     = ENV['http_proxy']
    config.proxy.https    = ENV['https_proxy']
    config.proxy.no_proxy = 'localhost,127.0.0.1'
  end
  config.vm.box = 'centos/7'          # (d1)
  # config.vm.provider :virtualbox do |vb|
  #   vb.memory = '2048'
  # end
  config.vm.define :spring do |node|
    node.vm.hostname = 'spring-boot'  # (d2)
    node.vm.network :private_network, # (d3)
                    ip: '192.168.88.30'
    # 80番ポート
    node.vm.network :forwarded_port,
                    guest: 80,
                    host: 8080,
                    auto_correct: true
    # Active MQの管理画面
    node.vm.network :forwarded_port,
                    guest: 8161,
                    host: 38161,
                    auto_correct: true
    # Active MQのプロトコル
    node.vm.network :forwarded_port,
                    guest: 61616,
                    host: 31616,
                    auto_correct: true
    # MongoDBのプロトコル
    node.vm.network :forwarded_port,
                    guest: 27017,
                    host: 37017,
                    auto_correct: true
  end
  config.vm.provision :shell,         # (d5)
                      path: 'bootstrap.sh'
end
