version: 2
jobs:
  build:
    working_directory: ~/spring-boot-crawler
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: spring-boot-crawler-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: spring-boot-crawler-{{ checksum "pom.xml" }}
      - add_ssh_keys:
          fingerprints:
            - "cd:3d:f8:a3:66:96:4f:af:41:b6:51:33:13:f5:67:0d"
      # - run: mvn package
      - run: cp .circleci/settings.xml $HOME/.m2/settings.xml
      - run: git config --global user.name "circle-ci"
      - run: git config --global user.email "circle@circle-ci.org"
      - run: mvn -X --batch-mode release:prepare release:perform
      # - run: mvn site

