version: 2
jobs:
  build:
    working_directory: ~/spring-boot-crawler
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: spring-boot-crawler-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: spring-boot-crawler-{{ checksum "pom.xml" }}
      - run: mvn package
