version: 2
jobs:
  build:
    working_directory: ~/spring-boot-crawler
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - restore_cache:
          key: spring-boot-crawler-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: spring-boot-crawler-{{ checksum "pom.xml" }}
      - add_ssh_keys:
          fingerprints:
            - "f4:5e:62:4b:94:09:0d:7c:42:2c:f5:9f:f1:ce:a5:e7"
      # - run: mvn package
      - run: mvn --batch-mode release:prepare release:perform
